# Generated by Django 5.2.4 on 2025-09-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='panchayat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
