# Generated by Django 5.2.4 on 2025-09-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location_panchayat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Temporarily stores the generated password for display in admin/manage page', max_length=128, null=True),
        ),
    ]
