# Generated by Django 5.2.4 on 2025-09-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solve_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_solutions/images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='solve_video',
            field=models.FileField(blank=True, null=True, upload_to='complaint_solutions/videos/'),
        ),
    ]
